package:
  name: clairvoyante
  version: 1.0

source:
  url: https://github.com/aquaskyline/Clairvoyante/releases/download/v1/Clairvoyante_v1.0.zip
  md5: 58e1c5435dabd56e7412260fac4b832a

build:
  number: 1
  skip: True #[osx]

channels:
    - defaults
    - conda-forge

requirements:
  run:
    - python=2.7
    - intervaltree
    - python-blosc
    - pypy2.7
    - numpy
    - tensorflow
    - zlib

test:
  commands:
    - which clairvoyante.py
    - clairvoyante.py

about:
  home: 'https://github.com/aquaskyline/Clairvoyante'
  license: AGPLv3
  license_file: LICENSE.md
  summary: "A deep neural network based variant caller"
